var express = require('express');
var user = require('../controllers/user');
var welcome = require('../controllers/welcome');
var blog = require('../controllers/blog');
var admin = require('../controllers/admin');
var router = express.Router();
router.get('/', welcome.index);
router.get('/login', user.login);
router.get('/logout', user.logout);
router.get('/reg', user.reg);
router.post('/checkLogin',user.checkLogin);
router.post('/regist',user.regist);
router.get('/adminIndex',admin.adminIndex);
router.get('/blogType',admin.blogType);
router.post('/addBlogType',admin.addBlogType);
router.get('/newBlog',admin.newBlog);
router.post('/addBlog',admin.addBlog);
router.get('/blogs',admin.listBlogs);
router.get('/viewPost',blog.viewPost);
router.get('/delBlog', admin.delBlog);
module.exports = router;
